# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('face_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 1, 29, 1, 18, 30, 415310))),
                ('path', models.ImageField(blank=True, default='face/default.png', upload_to='face')),
            ],
        ),
        migrations.CreateModel(
            name='PersistedFace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 1, 29, 1, 18, 30, 415880))),
                ('persisted_id', models.CharField(max_length=255)),
                ('path', models.ImageField(blank=True, default='face/default.png', upload_to='face')),
            ],
        ),
    ]
