# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 29, 4, 39, 19, 519553)),
        ),
        migrations.AlterField(
            model_name='persistedface',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 29, 4, 39, 19, 520619)),
        ),
        migrations.AlterField(
            model_name='persistedface',
            name='path',
            field=models.ImageField(blank=True, default='picture/default.png', upload_to='picture'),
        ),
    ]
